# Generated by Django 5.2.4 on 2025-07-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('max_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('available_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fitness Classes',
                'db_table': 'fitness_class',
                'ordering': ['class_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('fitness_class', models.ForeignKey(db_column='fitness_class', on_delete=django.db.models.deletion.CASCADE, to='booking.fitnessclass')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-booking_time'],
                'unique_together': {('fitness_class', 'client_email')},
            },
        ),
    ]
